[package]
name = "folded-falcon"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
cyclotomic-rings = { git = "https://github.com/nethermindeth/latticefold", branch = "ev/r1cs-builder" }
latticefold = { git = "https://github.com/nethermindeth/latticefold", branch = "ev/r1cs-builder" }
#cyclotomic-rings = { path = "../latticefold/cyclotomic-rings" }
#latticefold = { path = "../latticefold/latticefold" }
rand = "0.8"
falcon-rust = "0.1.2"