name: Build and test code

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo test --release --workspace --verbose --no-run
    - name: Run tests
      run: cargo test --release --workspace --verbose
